[package]
name = "ktx2-tools"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "ktx2-compress"
path = "src/ktx2-compress.rs"

[[bin]]
name = "ktx2-info"
path = "src/ktx2-info.rs"

[[bin]]
name = "ktx2-to-dds"
path = "src/ktx2-to-dds.rs"

#[[bin]]
#name = "ktx2-bc6h-compress"
#path = "src/ktx2-bc6h-compress.rs"

[dependencies]
ddsfile = "0.5.1"
ktx2 = { git = "https://github.com/expenses/ktx2", branch = "as-bytes" }
pollster = "0.2.5"
zstd = "0.11.2"
#wgpu-bc6h-compression = { git = "https://github.com/expenses/wgpu-bc6h-compression" }
wgpu = { version = "0.12.0", features = ["spirv"] }
basis-universal = "0.2.0"
futures-intrusive = "0.4.0"
env_logger = "0.9.0"

[patch.crates-io]
wgpu = { path = "../../wgpu/wgpu" }

[patch."https://github.com/gfx-rs/naga"]
naga = { path = "../../naga" }